<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.mjitech.qa.test.AddSkuToCart" tests="6" time="4.812" ignored="0" failures="0" timestamp="30 十一月 2018 03:43:27 GMT" skipped="0" hostname="YLMF-1711181457" errors="1">
  <testcase name="getPayUrl" time="0.069" classname="com.mjitech.qa.test.AddSkuToCart"/>
  <testcase name="submitCart" time="0.223" classname="com.mjitech.qa.test.AddSkuToCart"/>
  <testcase name="get_order_detail" time="0.060" classname="com.mjitech.qa.test.AddSkuToCart"/>
  <testcase name="get_order_detail_by_takingnumber" time="0.001" classname="com.mjitech.qa.test.AddSkuToCart">
    <error type="java.lang.Error" message="Unresolved compilation problem: 
	JSONArray cannot be resolved to a type
">
      <![CDATA[java.lang.Error: Unresolved compilation problem: 
	JSONArray cannot be resolved to a type

	at com.mjitech.qa.test.AddSkuToCart.get_order_detail_by_takingnumber(AddSkuToCart.java:267)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- get_order_detail_by_takingnumber -->
  <testcase name="add_sku_to_cart" time="4.350" classname="com.mjitech.qa.test.AddSkuToCart"/>
  <testcase name="wxpay_callback_test" time="0.109" classname="com.mjitech.qa.test.AddSkuToCart"/>
</testsuite> <!-- com.mjitech.qa.test.AddSkuToCart -->
